language: ruby
before_script:
  - bundle exec rails db:setup
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
env:
  - TESTSCRIPT="bin/travis-tests"
  - TESTSCRIPT="bin/travis-mutant ApplicationPolicy"
  - TESTSCRIPT="bin/travis-mutant GalleryPicturePolicy"
  - TESTSCRIPT="bin/travis-mutant GalleryPolicy"
  - TESTSCRIPT="bin/travis-mutant NewsEntryPolicy"
  - TESTSCRIPT="bin/travis-mutant OrgaMessagePolicy"
  - TESTSCRIPT="bin/travis-mutant EventPolicy"
  - TESTSCRIPT="bin/travis-mutant ActionPolicy"
  - TESTSCRIPT="bin/travis-mutant ActionGroupPolicy"
  - TESTSCRIPT="bin/travis-mutant RolePolicy"
  - TESTSCRIPT="bin/travis-mutant UserPolicy"
script:
  - $TESTSCRIPT
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT