language: ruby
before_script: "bundle exec rails db:setup"
env:
  - TESTSCRIPT="bin/travis-tests"
  - TESTSCRIPT="bin/travis-mutant ProjectPolicy"
  - TESTSCRIPT="bin/travis-mutant UserPolicy"
script:
  - $TESTSCRIPT