language: ruby
addons:
  postgresql: "9.6"
  firefox: latest
services:
  - postgresql
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.21.0/geckodriver-v0.21.0-linux64.tar.gz
  - tar -xf geckodriver-v0.21.0-linux64.tar.gz -C bin
  - export PATH=$PATH:$PWD/bin
  - export MOZ_HEADLESS=1
  - gem update --system
  - gem install bundler
before_script:
  - bundle exec rails db:setup
  - yarn install
env:
  - TESTSCRIPT="bin/travis-tests"
  #- TESTSCRIPT="bin/travis-mutant ActionGroupPolicy"
  - TESTSCRIPT="bin/travis-mutant ActionPolicy"
  - TESTSCRIPT="bin/travis-mutant ApplicationPolicy"
  - TESTSCRIPT="bin/travis-mutant EventPolicy"
  - TESTSCRIPT="bin/travis-mutant GalleryPicturePolicy"
  - TESTSCRIPT="bin/travis-mutant GalleryPolicy"
  - TESTSCRIPT="bin/travis-mutant NewsEntryPolicy"
  - TESTSCRIPT="bin/travis-mutant OrgaMessagePolicy"
  - TESTSCRIPT="bin/travis-mutant RolePolicy"
  - TESTSCRIPT="bin/travis-mutant SubscriptionPolicy"
  - TESTSCRIPT="bin/travis-mutant TagPolicy"
  - TESTSCRIPT="bin/travis-mutant UserPolicy"
script:
  - $TESTSCRIPT
