language: ruby
before_script: "bundle exec rails db:setup; bundle exec rails db:fixtures:load"
env:
  - TESTSCRIPT="bin/travis-tests"
  - TESTSCRIPT="bin/travis-mutant ProjectPolicy"
script:
  - $TESTSCRIPT